# pyproject_example.toml
[project]
name = "my_project"
version = "0.1.0"
description = "Python sample project"
authors = [{name = "Your Name", email = "your@example.com"}]

[project.dependencies]
requests = "^2.28"
numpy = "^1.24"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
